[package]
name = "ga1axy_render"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
nalgebra = { version = "0.26", optional = true }
bytemuck = "1.5"
watertender = { git = "https://github.com/Masterchef365/watertender.git", branch = "main" }